### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by d0tzx01337** [ThaisenPM/Loader3#4]
how do you make an account

**Comment by SimDoes** [comment]
basically you just make a mybb forum which will take you like 2 hrs cause ya and then you have to fix the php file because it's broken and get a mysql database and maybe a reader if you want to be a pro programmer and then you still have to fix the c# code as well and then you find that you need a encrypter.exe and when you find it it will have 3 blank fields where you don't know what to put and then you've done all that and it still does not work. So I doubt anyone is going to seriously use this loader but if ppl are actually gonna fix this then they are gonna have to change so much that the signature will be very different :) 

p.s. all your passwords are sent in plain text so that is some pro lvl programming plus it could probably be cracked very easily

**Comment by ThaisenPM** [comment]
It's a MyBB loader
